### ISSUE TITLE
Not able to load document detail view in 0.0.2 

### ISSUE THREAD

**Issue by philippeowagner** [thomasbrueggemann/paperless-desktop#18]
<img width="486" alt="screen shot 2017-03-18 at 16 02 31" src="https://cloud.githubusercontent.com/assets/113043/24073225/77f6b002-0bf4-11e7-90d0-c70f1cd4c0fa.png">

and after that, no other request seems to be fired to load another detail view. 
The button on top are not working either beside when pressing the "Document" button on the most left, the search field appears. 

<img width="1207" alt="screen shot 2017-03-18 at 16 04 52" src="https://cloud.githubusercontent.com/assets/113043/24073243/cb6f421c-0bf4-11e7-84ed-2a8b29c05665.png">

On the detail page the link to download the PDF directly works on the view that caused the error and  triggered the alert.

**Comment by thomasbrueggemann** [comment]
Fixed in https://github.com/thomasbrueggemann/paperless-desktop/releases/tag/v0.0.3
