### ISSUE TITLE
Checkbox in settings to load Paperless with "DevTools" on or off.

### ISSUE THREAD

**Issue by philippeowagner** [thomasbrueggemann/paperless-desktop#19]
https://github.com/thomasbrueggemann/paperless-desktop/blob/master/main.js#L145

This could help for issues like this #17 and of course for #18 one.

**Comment by thomasbrueggemann** [comment]
That's a good idea! Should at least be included until paperless-desktop is "production-ready".

**Comment by thomasbrueggemann** [comment]
Implemented in https://github.com/thomasbrueggemann/paperless-desktop/releases/tag/v0.0.3
