### ISSUE TITLE
support uploading new documents

### ISSUE THREAD

**Issue by HorayNarea** [thomasbrueggemann/paperless-desktop#25]
should be fairly easy to implement via HTTP POST consumption: https://paperless.readthedocs.io/en/latest/consumption.html#consumption-http

**Comment by thomasbrueggemann** [comment]
Thanks for checking in!
It all is relatively trivial, since the API is already there. Time is the only issue :) 
I think I even prepared the upload feature already. I'd be happy to see and merge any contributions!

**Comment by HorayNarea** [comment]
I have absolutely zero experience in "native-web" development but I will try to look into it and submit a PR 😀

**Comment by thomasbrueggemann** [comment]
It's pretty much just a react application wrapped in an electron webview container :)

**Comment by thomasbrueggemann** [comment]
Note to self: Handling file-drops on Elecrton app looks pretty straightforward https://blog.dcpos.ch/how-to-make-your-electron-app-sexy

**Comment by thomasbrueggemann** [comment]
Uploading via drag&drop is now available, thanks to @NickBusey .

➡️[v0.0.12-alpha](https://github.com/thomasbrueggemann/paperless-desktop/releases/tag/0.0.12-alpha)
