### ISSUE TITLE
Only PDFs can be opened

### ISSUE THREAD

**Issue by OmgImAlexis** [thomasbrueggemann/paperless-desktop#31]
Trying to open a `jpg` that I processed with paperless just thrown an error that it's not a pdf.

**Comment by thomasbrueggemann** [comment]
Oh, thanks for the hint. I didn't know that it is possible to manage anything else than PDFs!

**Comment by thomasbrueggemann** [comment]
Opening images is now available in [0.0.13-alpha](https://github.com/thomasbrueggemann/paperless-desktop/releases/tag/0.0.13-alpha) thanks to @NickBusey
