### ISSUE TITLE
Reminders for Documents

### ISSUE THREAD

**Issue by thomasbrueggemann** [thomasbrueggemann/paperless-desktop#4]
Popup a Desktop Notification or something for certain documents. This is especially interesting for bills that need to be payed at a certain point in time.

**Comment by philippeowagner** [comment]
Adding reminders to documents is a great idea. I use this in my current Evernote environment all the time even far into the future. I think this should be implemented in the core of paperless and made available through the API as well.

**Comment by thomasbrueggemann** [comment]
Note to self: Now supported in [paperless](https://github.com/danielquinn/paperless/releases/tag/0.4.0)

**Comment by thomasbrueggemann** [comment]
Reminders are implemented now in [0.0.9-alpha](https://github.com/thomasbrueggemann/paperless-desktop/releases/tag/v0.0.9)
