### ISSUE TITLE
Problem with files upload

### ISSUE THREAD

**Issue by maxthev** [thomasbrueggemann/paperless-desktop#44]
Hi, 
I'm trying to upload files with the drag&drop feature of the desktop app, the app seems to work because i got this line on server logs:

`
"POST /push HTTP/1.1" 202 
`

but the file is not in the consume directory and do not appear in the document list.

Volumes on my docker-compose are like this:
```
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            - ../volume/consume:/consume
```

folder permission are like this:

`drwxrwxr-x    2 root     paperles    4.0K Jul 17 15:28 consume`

I dont understand where is the problem.
Thank you

## Specifications

  - Version of Paperless: 2.1.x
  - Version of Paperless-Desktop: 0.0.13-alpha
  - Platform: MacOS High Sierra 10.13.5

**Comment by thomasbrueggemann** [comment]
Generally sounds more like an issue of _paperless_ itself, or your setup of paperless, and not _paperless-desktop_. Since you got the HTTP 202 status.

**Comment by thomasbrueggemann** [comment]
@maxthev But why do you expect the file to be in the consume directory? I don't think that's how the /push endpoint works. It directly feeds the document into the datastore. The consume directory is an alternative concurrent approach to feed documents into paperless.

**Comment by maxthev** [comment]
Hum ok, I was thinking that the push approach was uploading to the consume directory too, my bad.

But the file does not appear in paperless anyway (web interface or desktop app). It's like the app get the file (HTTP 202) then nothing.

(Also, feel free to close the issue if you think it's not the right place for this kind of problems ^^ )

**Comment by NickBusey** [comment]
Actually to be clear, the file does go in to the consume directory with the /push endpoint.

I had a similar problem, and my issue was the the /consume directory mount point was not the same on the paperless docker container as the paperless_consumer container. You have to make sure both those containers mount the same folder to the same path.

**Comment by maxthev** [comment]
It's strange because in the docker-compose.yml.example, there is something about /consume in the volumes section of consumer but not in webserver.
I tried to add the same `- ../volume/consume:/consume` to webserver but now i don't have the http 202 anymore, juste nothing server side when i drag and drop a file.

**Comment by NickBusey** [comment]
Here is the compose setup I use, and uploads are working for me through the app. https://gitlab.com/NickBusey/HomelabOS/blob/master/roles/homelabos/templates/docker-compose.yml#L495

It's strange you're not getting anything any more, that is probably worth investigating more. Is there an error in the Developer Console of the desktop app?

**Comment by thomasbrueggemann** [comment]
Sorry for getting that wrong about the /push and the consume directory! Thanks for clarifying.

**Comment by maxthev** [comment]
Okey it's now working !
First, I based my docker-compose.yml on @NickBusey 's one.
Then, I saw that I forgotten the https in url in app setup tab. This caused issue with my client max body size too.
