### ISSUE TITLE
this repo is still being maintained?

### ISSUE THREAD

**Issue by thepill** [thomasbrueggemann/paperless-desktop#53]
is this repo is still being maintained? I see the last commits/merges are from february and there are open pull requests

thanks :)

**Comment by thomasbrueggemann** [comment]
Hey Benjamin,

I am unable to maintain the repository at the moment, due to a lack of spare time. Would you be interested in reviewing pull requests and maintaining this repo a bit? 

- Thomas

**Comment by jeremymeyers** [comment]
Hope this comes back!

**Comment by totti4ever** [comment]
won't
