### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by DickerPeter** [thomasbrueggemann/paperless-desktop#87]
Moin kurze Frage wurde der Support eingestellt davon bzw. wird nicht weiter betreut?

**Comment by thomasbrueggemann** [comment]
Ich hab seit Jahren nichtmehr daran weiterentwickelt. Das paperless Backend hat irgendwie eine sonderbare Wendung genommen und ich nutze Paperless selbst nicht mehr. Schaut so aus als wäre die aktuelle Web UI von paperless aber auch nutzbarer geworden!
